library(shiny)
library(dplyr)
library(tidyverse)
source("utils.R")

# Define the directory to save the responses
responses_dir <- "responses"  # Change this to your desired directory

# Create the directory if it doesn't exist
if (!dir.exists(responses_dir)) {
  dir.create(responses_dir)
}

# Define the responses CSV file to save the data
responses_dat <- "responses.csv"

# Read OpenAI data
openai_dat <- read_csv("openai_dat.csv")

# Get frequencies for OpenAI's Q1
resp1_freq <- preprocess(openai_dat$resp1)

# Get frequencies for OpenAI's Q2
resp2_freq <- preprocess(openai_dat$resp2)

# Get frequencies for OpenAI's Q3
resp3_freq <- preprocess(openai_dat$resp3)

# Get frequencies for OpenAI's Q4
resp4_freq <- preprocess(openai_dat$resp4)

# Get frequencies for OpenAI's Q5
resp5_freq <- preprocess(openai_dat$resp5)

# Get frequencies for OpenAI's Q6
resp6_freq <- preprocess(openai_dat$resp6)

#### User Interface ####
ui <- fluidPage(
  titlePanel("Predict the Next Word(s)"),
  p("So far, we’ve discussed how LLMs generate text with word embeddings to predict the next word in a sentence."),
  p("In this activity, you will better understand how LLMs predict the words they use to craft sentences."),
  p("This exercise will help you appreciate the complexity and capabilities of AI in natural language processing."),
  p("First, you'll be asked to fill in the blanks for three simple sentences where only one word is missing."),
  p("Then, you'll complete three more sentences which require you to fill in multiple words."),
  p("Afterward, you'll see how your peers completed each phrase."),
  p("You'll use these findings to compare your inputs with different probabilities that could be generated by an AI model and reflect on any differences."),
  p("To get started, click ", tags$b("Next"), " to proceed to the next course item."),
  
  sidebarPanel(
    width = 12,
    
    # Dynamic question generation with aesthetic elements
    lapply(1:6, function(q_num) {
      question_input <- textInput(inputId = paste0("response_q", q_num), label = paste("Question", q_num, ":"))
      submit_button <- actionButton(inputId = paste0("submit_q", q_num), label = paste("Submit Response for Question", q_num))
      
      # Returning the layout for each question
      fluidRow(
        column(
          width = 12,
          question_input,
          submit_button,
          br(),
          column(6, plotOutput(paste0("histogram", q_num))),  # respQn plot
          column(6, plotOutput(paste0("histogram_openai_", q_num)))   # openaiQn plot
        ),
        textOutput(paste0("warning_Q", q_num)),  # Warning message specific to each question
        br(),
         # Individual submit button with updated label
      )
    }),
    
    br(),
    textOutput("warning")  # To show a warning message if fields are left empty
  )
)

#### Server logic ####
server <- function(input, output, session) {
  
  # Helper function to check if the user has already submitted a response
  has_responded <- function(question_num) {
    file_name <- file.path(responses_dir, paste0("responses_q", question_num, ".csv"))
    if (file.exists(file_name)) {
      existing_data <- read.csv(file_name)
      return(any(existing_data$hostname == session$clientData$url_hostname))
    }
    return(FALSE)
  }
  
  # Function to save response with proper appending
  save_response <- function(question_num, response) {
    response_data <- data.frame(
      question = paste("Question", question_num),
      response = response,
      hostname = session$clientData$url_hostname,
      stringsAsFactors = FALSE
    )
    
    file_name <- file.path(responses_dir, paste0("responses_q", question_num, ".csv"))
    
    # Append or create the CSV file correctly
    write.table(response_data, file = file_name, sep = ",", row.names = FALSE, 
                col.names = !file.exists(file_name), append = TRUE)
  }
  
  # Function to load responses for histograms
  load_responses <- function(question_num) {
    file_name <- file.path(responses_dir, paste0("responses_q", question_num, ".csv"))
    if (file.exists(file_name)) {
      read.csv(file_name, stringsAsFactors = FALSE)
    } else {
      data.frame(response = character(), hostname = character(), stringsAsFactors = FALSE)
    }
  }
  
  # Observe events for each question's submit button
  lapply(1:6, function(q_num) {
    observeEvent(input[[paste0("submit_q", q_num)]], {
      if (!has_responded(q_num)) {
        save_response(q_num, input[[paste0("response_q", q_num)]])
        showNotification("Response saved successfully.")
      } else {
        showNotification("You have already submitted a response for this question.", type = "error")
      }
    })
  })
  
  # Reactive values to hold the response data for histograms
  responses <- lapply(1:6, load_responses)
  
  # Histogram for each question
  lapply(1:6, function(q_num) {
    output[[paste0("histogram", q_num)]] <- renderPlot({
      response_data <- responses[[q_num]]
      histplot(response_data$response, newword = input[[paste0("response_q", q_num)]], 
               ip = session$clientData$url_hostname, main = paste("Human Distribution for Question", q_num), 
               charmax = 30, maxbars = 4)
    })
    
    output[[paste0("histogram_openai_", q_num)]] <- renderPlot({
      histplot(get(paste0("resp", q_num, "_freq"))$Value, newword = input[[paste0("response_q", q_num)]], 
               ip = session$clientData$url_hostname, main = paste("OpenAI Distribution for Question", q_num), 
               charmax = 30, maxbars = 4)
    })
  })
}

# Run the application 
shinyApp(ui = ui, server = server)
